import type { ExportBundleV1, Item, Measurement, Option, Room } from "@/lib/domain";
import { nowMs } from "@/lib/format";
import { DEFAULT_HOME } from "@/data/seed";

function t() {
  // Deterministic-ish timestamp for example bundle.
  return nowMs();
}

export function getTownHollywoodExampleBundle(): ExportBundleV1 {
  const ts = t();

  const rooms: Room[] = [
    { id: "Living", sort: 0, notes: "Great room = living + dining zones.", createdAt: ts, updatedAt: ts },
    { id: "Dining", sort: 1, notes: "", createdAt: ts, updatedAt: ts },
    { id: "Master", sort: 2, notes: "", createdAt: ts, updatedAt: ts },
    { id: "Bedroom2", sort: 3, notes: "Guest/office combo: keep closet clearance.", createdAt: ts, updatedAt: ts },
    { id: "Balcony", sort: 4, notes: "243 sq ft exterior. Measure usable rectangle between railings/walls.", createdAt: ts, updatedAt: ts },
    { id: "Entry", sort: 5, notes: "", createdAt: ts, updatedAt: ts },
    { id: "Kitchen", sort: 6, notes: "", createdAt: ts, updatedAt: ts },
    { id: "Bath", sort: 7, notes: "", createdAt: ts, updatedAt: ts },
  ];

  const measurements: Measurement[] = [
    { id: "m_greatroom_sofa_wall", room: "Living", sort: 0, label: "Great Room: sofa wall (longest clear wall)", valueIn: 168, confidence: "med", createdAt: ts, updatedAt: ts },
    { id: "m_greatroom_sofa_to_tv", room: "Living", sort: 1, label: "Great Room: sofa-to-TV wall distance", valueIn: 132, confidence: "med", createdAt: ts, updatedAt: ts },
    { id: "m_dining_zone_w", room: "Dining", sort: 0, label: "Dining zone width", valueIn: 96, createdAt: ts, updatedAt: ts },
    { id: "m_dining_zone_d", room: "Dining", sort: 1, label: "Dining zone depth", valueIn: 72, createdAt: ts, updatedAt: ts },
    { id: "m_master_bed_wall", room: "Master", sort: 0, label: "Master: bed-wall length", valueIn: 144, createdAt: ts, updatedAt: ts },
    { id: "m_master_depth", room: "Master", sort: 1, label: "Master: bed wall to opposite wall", valueIn: 128, createdAt: ts, updatedAt: ts },
    { id: "m_master_dresser_wall", room: "Master", sort: 2, label: "Master: dresser wall length", valueIn: 90, createdAt: ts, updatedAt: ts },
    { id: "m_b2_best_wall", room: "Bedroom2", sort: 0, label: "Bedroom 2: best wall for bed/desk", valueIn: 120, createdAt: ts, updatedAt: ts },
    { id: "m_b2_width", room: "Bedroom2", sort: 1, label: "Bedroom 2: room width (approx)", valueIn: 110, createdAt: ts, updatedAt: ts },
    { id: "m_balcony_len", room: "Balcony", sort: 0, label: "Balcony: usable length", valueIn: 220, createdAt: ts, updatedAt: ts },
    { id: "m_balcony_depth", room: "Balcony", sort: 1, label: "Balcony: usable depth", valueIn: 120, createdAt: ts, updatedAt: ts },
  ];

  const items: Item[] = [
    {
      id: "i_sofa",
      name: "Sofa",
      room: "Living",
      category: "Sofa",
      status: "Shortlist",
      priority: 1,
      sort: 0,
      qty: 1,
      price: null,
      store: null,
      link: "https://www.article.com",
      notes: "Target 84-96 in. Keep walkway clear to dining zone.",
      dimensions: { wIn: 92, dIn: 39, hIn: 34 },
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "i_tv_console",
      name: "TV console",
      room: "Living",
      category: "TV Console",
      status: "Idea",
      priority: 2,
      sort: 1,
      qty: 1,
      notes: "60-84 in wide, depth 15-18 in.",
      dimensions: { wIn: 72, dIn: 18, hIn: null },
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "i_dining_table",
      name: "Dining table",
      room: "Dining",
      category: "Dining Table",
      status: "Idea",
      priority: 2,
      sort: 0,
      qty: 1,
      notes: "Round 42-48 in or rectangular 60x36 in.",
      dimensions: { wIn: 60, dIn: 36, hIn: 30 },
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "i_master_bed",
      name: "Bed (Master)",
      room: "Master",
      category: "Bed",
      status: "Selected",
      priority: 1,
      sort: 0,
      qty: 1,
      notes: "Queen for clearance (aim 24-30 in each side).",
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "i_dresser",
      name: "Dresser",
      room: "Master",
      category: "Dresser",
      status: "Idea",
      priority: 2,
      sort: 1,
      qty: 1,
      dimensions: { wIn: 60, dIn: 18, hIn: null },
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "i_b2_combo",
      name: "Desk / Daybed (Bedroom 2)",
      room: "Bedroom2",
      category: "Office / Guest",
      status: "Idea",
      priority: 2,
      sort: 0,
      qty: 1,
      notes: "Decide guest vs office; keep closet clearance.",
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "i_balcony_set",
      name: "Balcony set",
      room: "Balcony",
      category: "Outdoor",
      status: "Idea",
      priority: 3,
      sort: 0,
      qty: 1,
      notes: "Bistro (30-36 in round) or lounge chairs + small table.",
      createdAt: ts,
      updatedAt: ts,
    },
  ];

  const options: Option[] = [
    {
      id: "o_sofa_article_solae",
      itemId: "i_sofa",
      title: "Article - Solae (example)",
      sort: 0,
      store: "Article",
      link: "https://www.article.com",
      price: 1999,
      shipping: 99,
      taxEstimate: 180,
      discount: 0,
      promoCode: null,
      dimensionsText: "90x39x34 in",
      notes: "Check seat depth + fabric. Verify delivery window.",
      selected: false,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "o_sofa_cb2_range",
      itemId: "i_sofa",
      title: "CB2 - Range sectional (example)",
      sort: 1,
      store: "CB2",
      link: "https://www.cb2.com",
      price: 2899,
      shipping: 199,
      taxEstimate: 260,
      discount: 150,
      promoCode: "WELCOME15",
      dimensionsText: "92x64x32 in",
      notes: "Confirm chaise side works for plan.",
      selected: false,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "o_dining_we_60x36",
      itemId: "i_dining_table",
      title: "West Elm - 60x36 (example)",
      sort: 0,
      store: "West Elm",
      link: null,
      price: 899,
      shipping: 149,
      taxEstimate: 90,
      discount: 0,
      promoCode: null,
      dimensionsText: "60x36x30 in",
      notes: "Confirm seating and walkway clearance.",
      selected: false,
      createdAt: ts,
      updatedAt: ts,
    },
  ];

  return {
    version: 1,
    exportedAt: new Date(ts).toISOString(),
    home: DEFAULT_HOME,
    rooms,
    measurements,
    items,
    options,
  };
}
